_wandb:
    value:
        cli_version: 0.25.1
        e:
            17p6brz2b4t08d5rc6yiq6f2yrtvwndp:
                args:
                    - --local_rank=0
                    - --data_path
                    - openai/summarize_from_feedback
                    - --data_split
                    - 2,4,4
                    - --actor_model_name_or_path
                    - /home/soo/yejin/CD-RLHF/models/gemma-2b-tldr-sft
                    - --critic_model_name_or_path
                    - /home/soo/yejin/CD-RLHF/models/gemma-2b-tldr-rm/step_18572
                    - --num_padding_at_beginning
                    - "0"
                    - --per_device_generation_batch_size
                    - "1"
                    - --per_device_training_batch_size
                    - "1"
                    - --generation_batches
                    - "1"
                    - --ppo_epochs
                    - "1"
                    - --max_answer_seq_len
                    - "512"
                    - --max_prompt_seq_len
                    - "512"
                    - --actor_learning_rate
                    - "8e-6"
                    - --critic_learning_rate
                    - "1e-5"
                    - --actor_weight_decay
                    - "0.1"
                    - --critic_weight_decay
                    - "0.1"
                    - --num_train_epochs
                    - "1"
                    - --lr_scheduler_type
                    - linear
                    - --gradient_accumulation_steps
                    - "32"
                    - --end_of_conversation_token
                    - <eos>
                    - --actor_dropout
                    - "0.0"
                    - --warmup_ratio
                    - "0.1"
                    - --deepspeed
                    - --seed
                    - "1234"
                    - --actor_zero_stage
                    - "3"
                    - --critic_zero_stage
                    - "3"
                    - --output_dir
                    - /home/soo/yejin/CD-RLHF/models/gemma-2b-tldr-cdrlhf
                    - --icm_learning_rate
                    - "1e-5"
                    - --eta
                    - "0.04"
                    - --cdrlhf_topk
                    - "1"
                    - --sample_size
                    - "1000"
                    - --kl_ctl
                    - "0.05"
                    - --print_answers
                    - --print_answers_interval
                    - "100"
                    - --save_steps
                    - "1000"
                    - --enable_wandb
                    - --project_name
                    - CD_RLHF
                codePath: applications/DeepSpeed-Chat/training/step3_rlhf_finetuning/main.py
                codePathLocal: main.py
                cpu_count: 192
                cpu_count_logical: 192
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "15147421802496"
                        used: "10258468491264"
                email: a2000yejin@snu.ac.kr
                executable: /home/soo/miniconda3/envs/cd_rlhf/bin/python3.10
                git:
                    commit: 467189a5b437cf31208372821cf8fcb8cf77c095
                    remote: https://github.com/ernie-research/CD-RLHF.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-7203fcf7-079e-0b87-e7d5-0e147a8bd6ba
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-fb7c18d7-3bc3-030d-94a3-b5ab4d8e2209
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-1b179fd9-cf66-170f-84ba-b3d94d3a220c
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-dc9fc490-e0a2-6493-e810-6ccfc2015bba
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-56b8f91f-dc15-1ac9-e228-230355c34197
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-e1ce4c49-62ff-04f4-1881-02b6b030aaca
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-0e472f99-2575-5b74-f269-3b9c00f9aa93
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-1f7ec963-88c1-5822-674b-681a4e9bb4fc
                host: vega
                memory:
                    total: "811218989056"
                os: Linux-6.8.0-79-generic-x86_64-with-glibc2.39
                program: /home/soo/yejin/CD-RLHF/applications/DeepSpeed-Chat/training/step3_rlhf_finetuning/main.py
                python: CPython 3.10.20
                root: /home/soo/yejin/CD-RLHF/applications/DeepSpeed-Chat/training/step3_rlhf_finetuning
                startedAt: "2026-04-05T04:29:23.355186Z"
                writerId: 17p6brz2b4t08d5rc6yiq6f2yrtvwndp
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.20
            "5": 0.25.1
            "6": 4.41.2
            "12": 0.25.1
            "13": linux-x86_64
actor_dropout:
    value: 0
actor_gradient_checkpointing:
    value: false
actor_learning_rate:
    value: 8e-06
actor_lora_dim:
    value: 0
actor_lora_dropout:
    value: 0
actor_lora_learning_rate:
    value: 0.0005
actor_lora_module_name:
    value: decoder.layers.
actor_lora_scaling:
    value: 1
actor_model_name_or_path:
    value: /home/soo/yejin/CD-RLHF/models/gemma-2b-tldr-sft
actor_weight_decay:
    value: 0.1
actor_zero_stage:
    value: 3
add_eot_token:
    value: false
align_overflow:
    value: false
cdrlhf_topk:
    value: 1
compute_fp32_loss:
    value: false
critic_dropout:
    value: null
critic_gradient_checkpointing:
    value: false
critic_learning_rate:
    value: 1e-05
critic_lora_dim:
    value: 0
critic_lora_dropout:
    value: 0
critic_lora_learning_rate:
    value: 0.0005
critic_lora_module_name:
    value: decoder.layers.
critic_lora_scaling:
    value: 1
critic_model_name_or_path:
    value: /home/soo/yejin/CD-RLHF/models/gemma-2b-tldr-rm/step_18572
critic_weight_decay:
    value: 0.1
critic_zero_stage:
    value: 3
data_output_path:
    value: /tmp/data_files
data_path:
    value:
        - openai/summarize_from_feedback
data_split:
    value: 2,4,4
deepscale:
    value: false
deepscale_config:
    value: null
deepspeed:
    value: true
deepspeed_config:
    value: null
dtype:
    value: fp16
enable_ema:
    value: false
enable_hybrid_engine:
    value: false
enable_mixed_precision_lora:
    value: false
enable_tensorboard:
    value: false
enable_test_mode:
    value: false
enable_wandb:
    value: true
enable_zero3_generation_gather:
    value: false
end_of_conversation_token:
    value: <eos>
eta:
    value: 0.04
gamma:
    value: 1
generation_batches:
    value: 1
global_rank:
    value: 0
gradient_accumulation_steps:
    value: 32
gradient_accumulation_steps_actor:
    value: 32
icm_learning_rate:
    value: 1e-05
icm_zero_stage:
    value: 0
inference_tp_size:
    value: 1
kl_ctl:
    value: 0.05
lam:
    value: 0.95
local_rank:
    value: 0
lr_scheduler_type:
    value: LINEAR
max_answer_seq_len:
    value: 512
max_prompt_seq_len:
    value: 512
num_padding_at_beginning:
    value: 0
num_train_epochs:
    value: 1
num_warmup_steps:
    value: null
offload:
    value: false
offload_icm_model:
    value: false
offload_reference_model:
    value: false
only_optimize_lora:
    value: false
output_dir:
    value: /home/soo/yejin/CD-RLHF/models/gemma-2b-tldr-cdrlhf
per_device_generation_batch_size:
    value: 1
per_device_training_batch_size:
    value: 1
ppo_epochs:
    value: 1
preprocessing_num_workers:
    value: null
print_answers:
    value: true
print_answers_interval:
    value: 100
project_name:
    value: CD_RLHF
release_inference_cache:
    value: false
sample_size:
    value: 1000
save_steps:
    value: 1000
seed:
    value: 1234
temperature:
    value: 0.8
tensorboard_path:
    value: step3_tensorboard
test_stop_step:
    value: 0
tp_gather_partition_size:
    value: 8
unpin_actor_parameters:
    value: false
unsup_coef:
    value: 27.8
unsupervised_dataset_config_name:
    value: null
unsupervised_dataset_name:
    value: null
warmup_ratio:
    value: 0.1
